const data = [
  { text: "Qubit's top customers annual growth rate.", value: "140%" },
  { text: "Online sales generated by our customers in 2020.", value: "$20bn" },
  { text: "Ecommerce stores are growing faster with Qubit.", value: "364" },
  { text: "Personalized experiences delivered every hour.", value: "9.5m" },
  { text: "Shoppers influenced by Qubit every day.", value: "4.4m" },
  {
    text: "Incremental revenue generated by our customers in 2020.*",
    value: "$1.6bn",
  },
];

export default data;
